name: Prepare local env
description: Set up Node and cache npm downloads
runs:
  using: composite
  steps:
    - name: Setup Node
      # Use Node version specified in Volta config inside package.json
      uses: volta-cli/action@v4

    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: |
        echo "dir=$(npm config get cache)" >> "$GITHUB_OUTPUT"

    - name: Cache npm downloads
      uses: actions/cache@v4
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-npm-js-kit-${{ hashFiles('js-kit/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-js-kit-
