export const SRS_RECORD_DISCRIMINATOR = 2;
export const SRS_OWNER_TYPE_PUBKEY = 0;
export const SRS_OWNER_TYPE_TOKEN = 1;

export const SRS_ADDRESS_LENGTH = 32;
export const SRS_EXPIRY_LENGTH = 8;

export const SRS_RECORD_DISCRIMINATOR_OFFSET = 0;
export const SRS_RECORD_CLASS_OFFSET = SRS_RECORD_DISCRIMINATOR_OFFSET + 1;
export const SRS_RECORD_OWNER_TYPE_OFFSET =
  SRS_RECORD_CLASS_OFFSET + SRS_ADDRESS_LENGTH;
export const SRS_RECORD_OWNER_OFFSET = SRS_RECORD_OWNER_TYPE_OFFSET + 1;
export const SRS_RECORD_FROZEN_OFFSET =
  SRS_RECORD_OWNER_OFFSET + SRS_ADDRESS_LENGTH;
export const SRS_RECORD_EXPIRY_OFFSET = SRS_RECORD_FROZEN_OFFSET + 1;
export const SRS_RECORD_HEADER_LENGTH =
  SRS_RECORD_EXPIRY_OFFSET + SRS_EXPIRY_LENGTH;
export const SRS_RECORD_METADATA_OFFSET = SRS_RECORD_HEADER_LENGTH + 1 + 32;
