[package]
name = "sns-cli"
version = "3.0.0"
edition = "2021"
homepage = "https://www.sns.id/"
repository = "https://github.com/SolanaNameService/sns-sdk"
description = "A utility CLI for interacting with the Solana Name Service"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
tokio = { version = "1.14.1", features = ["macros", "rt-multi-thread"] }
solana-program = { workspace = true }
solana-sdk = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-client = { workspace = true }
solana-account-decoder = { workspace = true }
spl-associated-token-account = { workspace = true, features = ["no-entrypoint"] }
spl-name-service = { workspace = true, features = ["no-entrypoint"] }
sns-sdk = { version = "2.0.0", path = "../sns-sdk" }
prettytable-rs = "0.10.0"
serde_json = "1.0.94"
serde = { version = "1.0.153", features = ["derive"] }
indicatif = "0.17.3"
regex = "1.7.1"
anyhow = "1.0.69"
console = "0.15.5"

[[bin]]
name = "sns"
path = "src/main.rs"
